# Generated by Django 3.0.3 on 2020-03-01 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='考试名称')),
                ('exam_date', models.DateField(blank=True, null=True, verbose_name='考生日期')),
                ('total_time', models.IntegerField(blank=True, help_text='时长按照分钟填写', null=True, verbose_name='时长')),
                ('institute', models.CharField(blank=True, max_length=20, null=True, verbose_name='学院')),
                ('major', models.CharField(blank=True, max_length=20, null=True, verbose_name='专业')),
                ('tip', models.TextField(blank=True, null=True, verbose_name='考生须知')),
                ('paper', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='paper.Paper', verbose_name='试卷')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'ordering': ['id'],
            },
        ),
    ]
