# Generated by Django 3.0.3 on 2020-03-03 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='考试名称')),
                ('exam_date', models.DateField(default='', verbose_name='考试日期')),
                ('total_time', models.PositiveSmallIntegerField(default=120, help_text='时长按照分钟填写', verbose_name='时长')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('tips', models.TextField(default='', verbose_name='考生须知')),
            ],
            options={
                'verbose_name': '考试',
                'verbose_name_plural': '考试',
                'db_table': 'exam_info',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='试卷名称')),
                ('score', models.PositiveSmallIntegerField(default=100, verbose_name='总分')),
                ('choice_number', models.PositiveSmallIntegerField(default=10, verbose_name='选择题数')),
                ('fill_number', models.PositiveSmallIntegerField(default=10, verbose_name='填空题数')),
                ('judge_number', models.PositiveSmallIntegerField(default=10, verbose_name='判断题数')),
                ('program_number', models.PositiveSmallIntegerField(default=10, verbose_name='编程题数')),
                ('level', models.CharField(choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], default='1', max_length=1, verbose_name='难度等级')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(default='', verbose_name='分数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建日期')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改日期')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.Exam', verbose_name='考试')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.Student', verbose_name='学生')),
            ],
            options={
                'verbose_name': '成绩',
                'verbose_name_plural': '成绩',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='paper',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='exam.Paper', verbose_name='试卷'),
        ),
    ]
