# Generated by Django 3.0.3 on 2020-03-01 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200301_2320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exam',
            old_name='tip',
            new_name='tips',
        ),
    ]
