# Generated by Django 3.0.3 on 2020-03-01 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20200301_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='total_time',
            field=models.TimeField(blank=True, help_text='时长按照分钟填写', null=True, verbose_name='时长'),
        ),
    ]
