# Generated by Django 3.0.3 on 2020-03-01 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200302_0104'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='exam',
            table='exam_info',
        ),
    ]
