# Generated by Django 3.0.3 on 2020-04-21 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_auto_20200421_2322'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exercise',
            new_name='Practice',
        ),
    ]
