# Generated by Django 3.0.3 on 2020-04-23 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20200422_0005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recode',
            old_name='exercise',
            new_name='practice',
        ),
    ]
