# Generated by Django 3.0.3 on 2020-04-24 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20200423_2333'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Recode',
        ),
    ]
