# Generated by Django 3.0.3 on 2020-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_practice_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clazz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=20, verbose_name='年级')),
                ('major', models.CharField(max_length=20, verbose_name='专业')),
                ('clazz', models.CharField(max_length=20, verbose_name='班级')),
            ],
            options={
                'verbose_name': '班级',
                'verbose_name_plural': '班级',
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='exam',
            name='students',
        ),
        migrations.AddField(
            model_name='exam',
            name='clazzs',
            field=models.ManyToManyField(to='exam.Clazz', verbose_name='参加考试的班级'),
        ),
    ]
