# Generated by Django 3.0.3 on 2020-03-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Course',
        ),
    ]
