# Generated by Django 3.0.3 on 2020-04-25 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicerecord',
            name='your_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='your_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='your_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='your_answer',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='你的作答'),
        ),
    ]
