# Generated by Django 3.0.3 on 2020-04-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0002_auto_20200425_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='programrecord',
            name='cmd_msg',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='输出结果'),
        ),
    ]
