# Generated by Django 3.0.3 on 2020-04-25 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('record', '0003_programrecord_cmd_msg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choicerecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='fillrecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='judgerecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='你的作答'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='cmd_msg',
            field=models.TextField(blank=True, null=True, verbose_name='输出结果'),
        ),
        migrations.AlterField(
            model_name='programrecord',
            name='your_answer',
            field=models.TextField(blank=True, null=True, verbose_name='你的作答'),
        ),
    ]
