# Generated by Django 3.0.3 on 2020-03-03 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('男', '男'), ('女', '女')], default='男', max_length=1, verbose_name='性别')),
                ('title', models.CharField(choices=[('讲师', '讲师'), ('副教授', '副教授'), ('教授', '教授')], default='讲师', max_length=5, verbose_name='职称')),
                ('institute', models.CharField(default='', max_length=20, verbose_name='学院')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '教师',
                'verbose_name_plural': '教师',
                'db_table': 'user_teacher',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='', max_length=1, verbose_name='性别')),
                ('year', models.CharField(choices=[('2016', '2016级'), ('2017', '2017级'), ('2018', '2018级'), ('2019', '2019级')], default='', max_length=4, verbose_name='年级')),
                ('major', models.CharField(default='', max_length=20, verbose_name='专业')),
                ('clazz', models.CharField(default='', max_length=20, verbose_name='班级')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'db_table': 'user_student',
                'ordering': ['id'],
            },
        ),
    ]
