# Generated by Django 3.0.3 on 2020-03-01 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20, null=True, verbose_name='试卷名称')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='总分')),
                ('choice_num', models.IntegerField(blank=True, null=True, verbose_name='选择题数')),
                ('fill_question', models.IntegerField(blank=True, null=True, verbose_name='填空题数')),
                ('judge_question', models.IntegerField(blank=True, null=True, verbose_name='判断题数')),
                ('program_question', models.IntegerField(blank=True, null=True, verbose_name='编程题数')),
                ('level', models.CharField(blank=True, choices=[('1', '入门'), ('2', '简单'), ('3', '普通'), ('4', '较难'), ('5', '困难')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'ordering': ['id'],
            },
        ),
    ]
