# Generated by Django 3.0.3 on 2020-03-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paper', '0003_auto_20200302_0104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paper',
            name='choice_num',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='fill_num',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='judge_num',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='program_num',
        ),
        migrations.AddField(
            model_name='paper',
            name='choice_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='选择题数'),
        ),
        migrations.AddField(
            model_name='paper',
            name='fill_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='填空题数'),
        ),
        migrations.AddField(
            model_name='paper',
            name='judge_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='判断题数'),
        ),
        migrations.AddField(
            model_name='paper',
            name='program_number',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='编程题数'),
        ),
        migrations.AlterField(
            model_name='paper',
            name='score',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='总分'),
        ),
        migrations.AlterModelTable(
            name='paper',
            table='paper_info',
        ),
    ]
